const checkboxArray = [
  {"code": "648", "crime": "Arson", "checked": true},
  {"code": "230", "crime": "Aggravated Assault With a Deadly Weapon", "checked": true},
  {"code": "231", "crime": "Assault with Deadly Weapon on Police Officer", "checked": true},
  {"code": "220", "crime": "Attempted Robbery", "checked": true},
  {"code": "622", "crime": "Battery on a Firefighter", "checked": true},
  {"code": "623", "crime": "Battery Police", "checked": true},
  {"code": "624", "crime": "Battery - Simple Assault", "checked": true},
  {"code": "860", "crime": "Battery with Sexual Contact", "checked": true},
  {"code": "480", "crime": "Bike Stolen", "checked": true},
  {"code": "755", "crime": "Bomb Scare", "checked": true},
  {"code": "761", "crime": "Brandish Weapon", "checked": true},
  {"code": "666", "crime": "Bunco Attempt", "checked": true},
  {"code": "662", "crime": "Bunco Grand Theft", "checked": true},
  {"code": "664", "crime": "Bunco Petty Theft", "checked": true},
  {"code": "310", "crime": "Burglary", "checked": true},
  {"code": "320", "crime": "Burglary - Attempted", "checked": true},
  {"code": "330", "crime": "Burglary from Vehicle", "checked": true},
  {"code": "410", "crime": "Attempted Burglary from Vehicle", "checked": true},
  {"code": "235", "crime": "Child Abuse (Physical) - Aggravated Assault", "checked": true},
  {"code": "627", "crime": "Child Abuse (Physical) = Simple Assault", "checked": true},
  {"code": "813", "crime": "Child Annoying (17 & Under Did Not Touch Victim)", "checked": true},
  {"code": "812", "crime": "Crime Against Child", "checked": true},
  {"code": "237", "crime": "Child Neglect", "checked": true},
  {"code": "922", "crime": "Child Stealing", "checked": true},
  {"code": "903", "crime": "Contempt of Court", "checked": true},
  {"code": "660", "crime": "Couterfeit", "checked": true},
  {"code": "653", "crime": "Credit Cards Fraud use ($950.01+)", "checked": true},
  {"code": "110", "crime": "Criminal Homicide", "checked": true},
  {"code": "930", "crime": "Criminal Threats (No Weapon Displayed)", "checked": true},
  {"code": "943", "crime": "Cruelty to Animals", "checked": true},
  {"code": "951", "crime": "Defrauding Innkeeper (<$400)", "checked": true},
  {"code": "753", "crime": "Discharge Firearms/Shots Fired", "checked": true},
  {"code": "886", "crime": "Disturbing the Peace", "checked": true},
  {"code": "649", "crime": "Document Forgery/Stolen", "checked": true},
  {"code": "651", "crime": "Document Worthless", "checked": true},
  {"code": "433", "crime": "Driving Without Owner's Consent", "checked": true},
  {"code": "668", "crime": "Embezzlement Grand Theft ($950.01+)", "checked": true},
  {"code": "940", "crime": "Extortion", "checked": true},
  {"code": "890", "crime": "Failure to Yield", "checked": true},
  {"code": "434", "crime": "False Imprisonment", "checked": true},
  {"code": "949", "crime": "Illegal Dumping", "checked": true},
  {"code": "850", "crime": "Indecent Exposure", "checked": true},
  {"code": "910", "crime": "Kidnapping", "checked": true},
  {"code": "920", "crime": "Kidnapping - Grand Attempt", "checked": true},
  {"code": "956", "crime": "Lewd Letters", "checked": true},
  {"code": "762", "crime": "Lewd Conduct", "checked": true},
  {"code": "820", "crime": "Oral Copulation", "checked": true},
  {"code": "625", "crime": "Other Assault", "checked": true},
  {"code": "946", "crime": "Other Miscellaneous Crime", "checked": true},
  {"code": "806", "crime": "Pandering", "checked": true},
  {"code": "932", "crime": "Peeping Tom", "checked": true},
  {"code": "352", "crime": "Pickpocket", "checked": true},
  {"code": "452", "crime": "Pickpocket Attempt", "checked": true},
  {"code": "805", "crime": "Pimping", "checked": true},
  {"code": "933", "crime": "Prowler", "checked": true},
  {"code": "351", "crime": "Purse Snatching", "checked": true},
  {"code": "451", "crime": "Purse Snatching Attempt", "checked": true},
  {"code": "122", "crime": "Rape Attempted", "checked": true},
  {"code": "121", "crime": "Rape Forcible", "checked": true},
  {"code": "438", "crime": "Reckless Driving", "checked": true},
  {"code": "437", "crime": "Resisting Arrest", "checked": true},
  {"code": "210", "crime": "Robbery", "checked": true},
  {"code": "815", "crime": "Sexual Penetration With a Foreign Object", "checked": true},
  {"code": "810", "crime": "Sex Unlawful", "checked": true},
  {"code": "443", "crime": "Shoplifting - Attempt", "checked": true},
  {"code": "343", "crime": "Shoplifting - Grand Theft ($950.01+)", "checked": true},
  {"code": "442", "crime": "Shoplifting - Petty Theft (< $950)", "checked": true},
  {"code": "821", "crime": "Sodomy - Sexual Contact Between Penis of One Person to Anus of Another Person", "checked": true},
  {"code": "236", "crime": "Spousal (Cohabitative) Abuse - Aggravated Assault", "checked": true},
  {"code": "763", "crime": "Stalking", "checked": true},
  {"code": "475", "crime": "Theft Coin Machine - Attempted", "checked": true},
  {"code": "473", "crime": "Theft Coin Machine - Grand ($950.01+)", "checked": true},
  {"code": "474", "crime": "Theft Coin Machine - Petty (< $950)", "checked": true},
  {"code": "421", "crime": "Theft from Motor Vehicle - Attempt", "checked": true},
  {"code": "331", "crime": "Theft from Motor Vehicle - Grand ($400+)", "checked": true},
  {"code": "420", "crime": "Theft from Motor Vehicle - Petty ($950.01+)", "checked": true},
  {"code": "341", "crime": "Theft - Grand ($950.01+) Except Guns Fowl Livestock Produce", "checked": true},
  {"code": "354", "crime": "Theft of Identity", "checked": true},
  {"code": "350", "crime": "Theft Person", "checked": true},
  {"code": "441", "crime": "Theft Plain - Attempt", "checked": true},
  {"code": "440", "crime": "Theft Plain - Petty (< $950)", "checked": true},
  {"code": "647", "crime": "Throwing Object at Moving Vehicle", "checked": true},
  {"code": "470", "crime": "Till Tap - Grand Theft ($950.01+)", "checked": true},
  {"code": "471", "crime": "Till Tap - Petty (< $950)", "checked": true},
  {"code": "997", "crime": "Traffic DR#", "checked": true},
  {"code": "888", "crime": "Trespassing", "checked": true},
  {"code": "661", "crime": "Unauthorized Computer Access", "checked": true},
  {"code": "740", "crime": "Vandalism - Felony ($400+ All Church Vandalisms)", "checked": true},
  {"code": "745", "crime": "Vandalism - Misdemeanor (< $399)", "checked": true},
  {"code": "520", "crime": "Vehicle - Attempt Stolen", "checked": true},
  {"code": "510", "crime": "Vehicle Stolen", "checked": true},
  {"code": "900", "crime": "Violation of Court Order", "checked": true},
  {"code": "901", "crime": "Violation of Restraining Order", "checked": true},
  {"code": "902", "crime": "Violation of Temporary Restraining Order", "checked": true},
  {"code": "756", "crime": "Weapons Possession/Bombing",  "checked": true}
]

// export default checkboxArray;